const propertiesData = [
    {
      checked: true,
      status: "published",
      price: 'AED 62,000',
      frequency: 'Yearly',
      type: 'Apartment',
      studio: true,
      area: '391 sqft',
      description: 'Brand New | Fully Furnished | Near Metro Station',
      location: 'Prime Residency 3, Al Furjan, Dubai',
      verifiedDate: '7th of March',
      agent: {
        name: 'Sarah Johnson',
        imageUrl: 'agent.jpg',
        callNumber: '+971 55 123 4567',
        whatsappNumber: '+971 50 987 6543',
      },
      images: [
        'image.png',
        'image2.jpg',
        'image3.jpeg'
      ],
    },
    {
      checked: false,
      status: "published",
      price: 'AED 85,000',
      frequency: 'Yearly',
      type: 'Villa',
      studio: false,
      area: '1200 sqft',
      description: 'Spacious Family Villa | Private Garden | Quiet Community',
      location: 'Jumeirah Village Circle, Dubai',
      verifiedDate: '10th of March',
      agent: {
        name: 'Daniel Lee',
        imageUrl: 'agent.jpg',
        callNumber: '+971 55 234 5678',
        whatsappNumber: '+971 50 876 5432',
      },
      images: [
        'image.png',
        'image2.jpg',
        'image3.jpeg'
      ],
    },
    {
      checked: true,
      status: "pocketed",
      price: 'AED 45,000',
      frequency: 'Yearly',
      type: 'Studio Apartment',
      studio: true,
      area: '325 sqft',
      description: 'Cozy Studio | Near Downtown | Great Amenities',
      location: 'Business Bay, Dubai',
      verifiedDate: '5th of March',
      agent: {
        name: 'Emily Carter',
        imageUrl: 'agent.jpg',
        callNumber: '+971 55 345 6789',
        whatsappNumber: '+971 50 765 4321',
      },
      images: [
        'image.png',
        'image2.jpg',
        'image3.jpeg'
      ],
    },
    {
      checked: false,
      status: "pocketed",
      price: 'AED 120,000',
      frequency: 'Yearly',
      type: 'Penthouse',
      studio: false,
      area: '2500 sqft',
      description: 'Luxury Penthouse | Panoramic View | Private Pool',
      location: 'Downtown Dubai, Dubai',
      verifiedDate: '1st of March',
      agent: {
        name: 'Michael Roberts',
        imageUrl: 'agent.jpg',
        callNumber: '+971 55 456 7890',
        whatsappNumber: '+971 50 654 3210',
      },
      images: [
        'image.png',
        'image2.jpg',
        'image3.jpeg'
      ],
    },
    {
      checked: true,
      status: "published",
      price: 'AED 70,000',
      frequency: 'Yearly',
      type: 'Apartment',
      studio: true,
      area: '850 sqft',
      description: 'Modern Apartment | Balcony | Community View',
      location: 'Dubai Marina, Dubai',
      verifiedDate: '8th of March',
      agent: {
        name: 'Sophia Martinez',
        imageUrl: 'agent.jpg',
        callNumber: '+971 55 567 8901',
        whatsappNumber: '+971 50 543 2109',
      },
      images: [
        'image.png',
        'image2.jpg',
        'image3.jpeg'
      ],
    },
    {
      checked: false,
      status: "published",
      price: 'AED 95,000',
      frequency: 'Yearly',
      type: 'Townhouse',
      studio: true,
      area: '1500 sqft',
      description: 'Gated Community | Family Friendly | Close to Park',
      location: 'Arabian Ranches, Dubai',
      verifiedDate: '12th of March',
      agent: {
        name: 'Liam Johnson',
        imageUrl: 'agent.jpg',
        callNumber: '+971 55 678 9012',
        whatsappNumber: '+971 50 432 1098',
      },
      images: [
        'image.png',
        'image2.jpg',
        'image3.jpeg'
      ],
    },
    {
      checked: true,
      status: "pocketed",
      price: 'AED 58,000',
      frequency: 'Yearly',
      type: 'Apartment',
      studio: false,
      area: '680 sqft',
      description: 'Bright and Airy | High Floor | Fully Furnished',
      location: 'JLT, Dubai',
      verifiedDate: '14th of March',
      agent: {
        name: 'Olivia Davis',
        imageUrl: 'agent.jpg',
        callNumber: '+971 55 789 0123',
        whatsappNumber: '+971 50 321 0987',
      },
      images: [
        'image.png',
        'image2.jpg',
        'image3.jpeg'
      ],
    },
    {
        checked: true,
      status: "published",
        price: 'AED 75,000',
        frequency: 'Yearly',
        type: 'Apartment',
        studio: true,
        area: '850 sqft',
        description: 'Spacious 1BR | High Floor | Marina View',
        location: 'Marina Pinnacle, Dubai Marina, Dubai',
        verifiedDate: '10th of March',
        agent: {
          name: 'Ahmed Khalid',
          imageUrl: 'agent.jpg',
          callNumber: '+971 52 456 7890',
          whatsappNumber: '+971 50 654 3210',
        },
        images: [
            'image.png',
        'image2.jpg',
        'image3.jpeg'
        ],
      },
      {
        checked: true,
      status: "pocketed",
        price: 'AED 55,000',
        frequency: 'Yearly',
        type: 'Apartment',
        studio: true,
        area: '420 sqft',
        description: 'Modern Studio | Balcony | Near Downtown',
        location: 'Burj Al Nujoom, Downtown Dubai, Dubai',
        verifiedDate: '8th of March',
        agent: {
          name: 'Layla Mansour',
        imageUrl: 'agent.jpg',
          callNumber: '+971 56 789 0123',
          whatsappNumber: '+971 58 234 5678',
        },
        images: [
            'image.png',
        'image2.jpg',
        'image3.jpeg'
        ],
      },
      {
        checked: true,
      status: "pocketed",
        price: 'AED 90,000',
        frequency: 'Yearly',
        type: 'Apartment',
        studio: false,
        area: '1,200 sqft',
        description: 'Luxury 2BR | Sea View | Fully Upgraded',
        location: 'Shams 1, JBR, Dubai',
        verifiedDate: '5th of March',
        agent: {
          name: 'Omar Hassan',
          imageUrl: 'agent.jpg',
          callNumber: '+971 54 321 6789',
          whatsappNumber: '+971 57 789 1234',
        },
        images: [
        'image.png',
        'image2.jpg',
        'image3.jpeg'
        ],
      }
  ];
  
  export default propertiesData;